// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ9ct93DPotkxdirWd3hJBTxzMHxxsSho',
    appId: '1:57902414486:web:9dcabb91c88d00f616e0b7',
    messagingSenderId: '57902414486',
    projectId: 'assignment-rootally',
    authDomain: 'assignment-rootally.firebaseapp.com',
    storageBucket: 'assignment-rootally.appspot.com',
    measurementId: 'G-C0YSBW2R7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsCq_1IWkx8nGaF3HlthZa89fPi97Eocs',
    appId: '1:57902414486:android:30da9bf0695a1ff516e0b7',
    messagingSenderId: '57902414486',
    projectId: 'assignment-rootally',
    storageBucket: 'assignment-rootally.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFGRbRvH9LYbdq8jZV8hd31-lMFXvRz4',
    appId: '1:57902414486:ios:e9bc56706c0d31f516e0b7',
    messagingSenderId: '57902414486',
    projectId: 'assignment-rootally',
    storageBucket: 'assignment-rootally.appspot.com',
    iosClientId: '57902414486-qp1l1e3vsthhmofgm275j5s5693pn1ok.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
